// <auto-generated />
namespace banjiguanli.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update201911281441 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update201911281441));
        
        string IMigrationMetadata.Id
        {
            get { return "201911280641246_Update201911281441"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
